data:
  menus:
    - id: sys
      children:
        - id: flowableMgr
          name: 流程引擎
          icon: BranchesOutlined
          seq: 100
          children:
            - id: flowableModel
              name: 模型管理
              path: /flowable
              perms:
                - perm: flowableModel:design
                  name: 设计
                - perm: flowableModel:deploy
                  name: 部署


            - id: flowableMonitor
              name: 流程管理
              path: /flowable/monitor
              perms:
                - perm: flowableTask:setAssignee
                  name: 设置任务受理人

    - name: 我的任务
      id: flowableTask
      path: /flowable/task
      seq: -1
      refresh-on-tab-click: true
      message-count-url: /admin/flowable/my/todoCount
      perms:
        - perm: flowableTask
          name: 任务管理

